#!/usr/bin/env python3
"""Generate arithmetic regressions using Python integer multiplication and pow."""

import json
from pathlib import Path
import random
import subprocess

ROOT = Path(__file__).resolve().parents[1]
rng = random.Random(20260907)
out = ["// Generated by scripts/gen_arithmetic_tests.py; Python integers are the oracle."]


def limbs(value, count):
    return "array![" + ", ".join(str((value >> (64 * i)) & ((1 << 64) - 1))
                                 for i in range(count)) + "].span()"


def test(name, call, expected, k):
    out.extend([
        "#[test]", f"fn {name}() {{", f"    let got = {call};",
        f"    assert(vdf::limbs_eq(got.span(), {limbs(expected, k)}, {k}), 'Python oracle');",
        "}",
    ])


for k in (4, 8, 16, 32):
    bound = 1 << (64 * k)
    n = rng.randrange(bound // 2, bound) | 1
    cases = [
        ("maximal_operands", bound - 1, bound - 2, bound - 2),
        ("small_modulus_unreduced", bound // (1 << 64) + 1, bound - 1, bound - 1),
        ("zero", n, 0, n - 1), ("one", n, 1, n - 1),
        ("random_reduced", n, rng.randrange(n), rng.randrange(n)),
        ("random_unreduced", n, rng.randrange(n, bound), rng.randrange(n, bound)),
    ]
    for name, n, a, b in cases:
        call = (f"vdf::modmul({limbs(a, k)}, {limbs(b, k)}, {limbs(n, k)}, "
                f"{limbs(bound * bound // n, k + 1)}, {k})")
        test(f"modmul_{64 * k}_{name}", call, a * b % n, k)

vector = json.loads((ROOT / "vectors/vdf_vectors_512.json").read_text())[0]
n = int(vector["N"], 16)
for name, e, f in [
    ("zero_exponents", 0, 0), ("only_second_exponent", 0, 1),
    ("only_first_exponent", 1, 0), ("both_one", 1, 1),
    ("unequal_bit_lengths", 1 << 192, 1 << 128),
    ("dense_exponents", (1 << 256) - 1, (1 << 256) - 1),
    ("random_exponents", rng.getrandbits(256), rng.getrandbits(256)),
]:
    a, b = rng.randrange(n, 1 << 512), rng.randrange(n, 1 << 512)
    call = (f"vdf::joint_modpow({limbs(a, 8)}, {limbs(e, 4)}, {limbs(b, 8)}, "
            f"{limbs(f, 4)}, {limbs(n, 8)}, {limbs((1 << 1024) // n, 9)}, 8)")
    test(f"joint_{name}", call, pow(a, e, n) * pow(b, f, n) % n, 8)

path = ROOT / "cairo/lib/src/arithmetic_tests.cairo"
path.write_text("\n".join(out) + "\n")
subprocess.run(["scarb", "fmt", "src/arithmetic_tests.cairo"], cwd=ROOT / "cairo/lib", check=True)
print(f"{path}: 31 arithmetic tests regenerated")
